nohup python FindMoreWebPages.py 00 > 00.log & 
nohup python FindMoreWebPages.py 01 > 01.log & 
nohup python FindMoreWebPages.py 02 > 02.log & 
nohup python FindMoreWebPages.py 03 > 03.log & 
nohup python FindMoreWebPages.py 04 > 04.log & 
nohup python FindMoreWebPages.py 05 > 05.log & 
nohup python FindMoreWebPages.py 06 > 06.log & 
nohup python FindMoreWebPages.py 07 > 07.log & 
nohup python FindMoreWebPages.py 08 > 08.log & 
nohup python FindMoreWebPages.py 09 > 09.log & 
nohup python FindMoreWebPages.py 10 > 10.log & 
nohup python FindMoreWebPages.py 11 > 11.log & 