nohup python RawCount.py 00 > 00.log & 
nohup python RawCount.py 01 > 01.log & 
nohup python RawCount.py 02 > 02.log & 
nohup python RawCount.py 03 > 03.log & 
nohup python RawCount.py 04 > 04.log & 
nohup python RawCount.py 05 > 05.log & 
nohup python RawCount.py 06 > 06.log & 
nohup python RawCount.py 07 > 07.log & 
nohup python RawCount.py 08 > 08.log & 
nohup python RawCount.py 09 > 09.log & 
nohup python RawCount.py 10 > 10.log & 
nohup python RawCount.py 11 > 11.log & 
nohup python RawCount.py 12 > 12.log & 
nohup python RawCount.py 13 > 13.log & 
nohup python RawCount.py 14 > 14.log & 
nohup python RawCount.py 15 > 15.log & 
nohup python RawCount.py 16 > 16.log & 
nohup python RawCount.py 17 > 17.log & 
nohup python RawCount.py 18 > 18.log & 
nohup python RawCount.py 19 > 19.log & 
nohup python RawCount.py 20 > 20.log & 
nohup python RawCount.py 21 > 21.log & 
nohup python RawCount.py 22 > 22.log & 
nohup python RawCount.py 23 > 23.log & 
nohup python RawCount.py 24 > 24.log & 
nohup python RawCount.py 25 > 25.log & 
nohup python RawCount.py 26 > 26.log & 
nohup python RawCount.py 27 > 27.log & 
nohup python RawCount.py 28 > 28.log & 
nohup python RawCount.py 29 > 29.log & 
nohup python RawCount.py 30 > 30.log & 
nohup python RawCount.py 31 > 31.log & 
