nohup python ExtractEnPage.py 00 > 00.log & 
nohup python ExtractEnPage.py 01 > 01.log & 
nohup python ExtractEnPage.py 02 > 02.log & 
nohup python ExtractEnPage.py 03 > 03.log & 
nohup python ExtractEnPage.py 04 > 04.log & 
nohup python ExtractEnPage.py 05 > 05.log & 
nohup python ExtractEnPage.py 06 > 06.log & 
nohup python ExtractEnPage.py 07 > 07.log & 
nohup python ExtractEnPage.py 08 > 08.log & 
nohup python ExtractEnPage.py 09 > 09.log & 
nohup python ExtractEnPage.py 10 > 10.log & 
nohup python ExtractEnPage.py 11 > 11.log & 
nohup python ExtractEnPage.py 12 > 12.log & 
nohup python ExtractEnPage.py 13 > 13.log & 
nohup python ExtractEnPage.py 14 > 14.log & 
nohup python ExtractEnPage.py 15 > 15.log & 
nohup python ExtractEnPage.py 16 > 16.log & 
nohup python ExtractEnPage.py 17 > 17.log & 
nohup python ExtractEnPage.py 18 > 18.log & 
nohup python ExtractEnPage.py 19 > 19.log & 
